version: '3.8'

services:

  # Zookeeper
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"

  # Kafka
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "mastodon_stream:1:1"
    depends_on:
      - zookeeper

  # PostgreSQL
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mastodon_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Spark + Jupyter
  spark:
    image: jupyter/pyspark-notebook # ou peut-être mettre : spark_mastodon:latest
    container_name: spark
    ports:
      - "8888:8888"   # Jupyter
      - "4040-4045:4040-4045" # Spark UI
    environment:
      JUPYTER_ENABLE_LAB: "yes"
    volumes:
      - ./src:/home/jovyan/src
      - ./notebooks:/home/jovyan/notebooks
    depends_on:
      - kafka
      - postgres

volumes:
  postgres_data:
