version: '3.8'

services:

  # Zookeeper
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - mastodon_net

  # Kafka
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "mastodon_stream:1:1"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
    networks:
      - mastodon_net

  # PostgreSQL
  postgres:
    image: postgres:15
    container_name: mastodon_db
    environment:
      POSTGRES_USER: mastodon_user
      POSTGRES_PASSWORD: mastodon
      POSTGRES_DB: mastodon
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mastodon_net

  # Spark + Jupyter
  spark:
    image: jupyter/pyspark-notebook # ou peut-être mettre : spark_mastodon:latest
    container_name: spark
    ports:
      - "8888:8888"   # Jupyter
      - "4040-4045:4040-4045" # Spark UI
    environment:
      JUPYTER_ENABLE_LAB: "yes"
      PYSPARK_SUBMIT_ARGS: "--packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.1,org.postgresql:postgresql:42.6.0 pyspark-shell"
    volumes:
      - "./scripts:/home/jovyan/scripts"
      - "./notebooks:/home/jovyan/notebooks"
      - "./.env:/home/jovyan/.env"
    depends_on:
      - kafka
      - postgres
    networks:
      - mastodon_net

networks:
  mastodon_net:
    driver: bridge

volumes:
  postgres_data:
